import os
import yfinance as yf
from langchain_core.tools import tool
from fpdf import FPDF
from config import OUTPUT_REPORT_PATH

@tool
def get_stock_analysis(ticker: str) -> dict:
    """
    Fetches real-time market data, valuation metrics (P/E and P/B ratios), 
    and general business summaries from Yahoo Finance for a specified company ticker.
    """
    try:
        ticker_clean = ticker.strip().upper()
        stock = yf.Ticker(ticker_clean)
        info = stock.info
        
        return {
            "Ticker": ticker_clean,
            "Current Price": info.get("currentPrice", "N/A"),
            "Market Cap": f"${info.get('marketCap', 0):,}" if info.get('marketCap') else "N/A",
            "P/E Ratio": f"{info.get('trailingPE', 0):.2f}x" if info.get('trailingPE') else "N/A",
            "P/B Ratio": f"{info.get('priceToBook', 0):.2f}x" if info.get('priceToBook') else "N/A",
            "Business Summary": info.get("longBusinessSummary", "")[:500] + "..."
        }
    except Exception as e:
        return {"error": f"Failed to retrieve data for ticker '{ticker}': {str(e)}"}


class CustomStudentPDF(FPDF):
    def header(self):
        # Top corporate accent block
        self.set_fill_color(15, 23, 42) # Dark charcoal/navy
        self.rect(0, 0, 210, 28, 'F')
        
        self.set_font("Arial", "B", 15)
        self.set_text_color(255, 255, 255)
        self.cell(0, 5, "fin_intel Hub | Automated Financial Report", ln=True, align="C")
        self.set_font("Arial", "I", 8)
        self.set_text_color(148, 163, 184)
        self.cell(0, 5, "EQUITY RESEARCH & VALUATION BRIEF", ln=True, align="C")
        self.ln(15)

    def footer(self):
        self.set_y(-15)
        self.set_font("Arial", "I", 8)
        self.set_text_color(100, 116, 139)
        self.cell(0, 10, "fin_intel Analysis Engine • Academic Portfolio Asset", 0, 0, "L")
        self.cell(0, 10, f"Page {self.page_no()}", 0, 0, "R")


@tool
def generate_pdf_report(report_data: str) -> str:
    """
    Compiles complex analysis text generated by the LLM into a highly organized, 
    custom-styled PDF statement using native FPDF components.
    """
    try:
        pdf = CustomStudentPDF()
        pdf.set_auto_page_break(auto=True, margin=20)
        pdf.add_page()
        
        # Section 1 Header
        pdf.set_font("Arial", "B", 11)
        pdf.set_text_color(15, 23, 42)
        pdf.set_fill_color(59, 130, 246) # Blue marker
        pdf.rect(10, pdf.get_y() + 1, 3, 4, 'F')
        pdf.set_x(15)
        pdf.cell(0, 6, "1. Executive Core Summary & Background", ln=True)
        pdf.ln(3)
        
        # Parse the report lines to separate standard narrative text from raw metric key-values
        pdf.set_font("Arial", size=10)
        pdf.set_text_color(51, 65, 85)
        
        clean_text = report_data.encode('latin-1', 'ignore').decode('latin-1')
        lines = clean_text.split("\n")
        
        table_metrics = []
        narrative_lines = []
        
        for line in lines:
            if ":" in line and ("Price" in line or "Cap" in line or "Ratio" in line or "Ticker" in line):
                table_metrics.append(line.split(":", 1))
            elif line.strip():
                narrative_lines.append(line)
        
        # Print description narrative text first
        pdf.multi_cell(0, 6, "\n".join(narrative_lines[:3]))
        pdf.ln(6)
        
        # Section 2 Header: Tabular Metrics Grid
        if table_metrics:
            pdf.set_font("Arial", "B", 11)
            pdf.set_text_color(15, 23, 42)
            pdf.set_fill_color(59, 130, 246)
            pdf.rect(10, pdf.get_y() + 1, 3, 4, 'F')
            pdf.set_x(15)
            pdf.cell(0, 6, "2. Key Fundamental Valuation Metrics", ln=True)
            pdf.ln(4)
            
            # Print Table Headers
            pdf.set_font("Arial", "B", 9.5)
            pdf.set_fill_color(241, 245, 249) # Light grey header row
            pdf.set_text_color(15, 23, 42)
            pdf.cell(85, 7, " Financial Indicator", border=1, fill=True)
            pdf.cell(105, 7, " Reported Metric Value", border=1, fill=True, ln=True)
            
            # Print Data Rows dynamically with alternating row colors
            pdf.set_font("Arial", size=9.5)
            pdf.set_text_color(51, 65, 85)
            fill_toggle = False
            
            for key, val in table_metrics:
                pdf.set_fill_color(248, 250, 252) if fill_toggle else pdf.set_fill_color(255, 255, 255)
                pdf.cell(85, 7, f" {key.strip()}", border=1, fill=True)
                pdf.cell(105, 7, f" {val.strip()}", border=1, fill=True, ln=True)
                fill_toggle = not fill_toggle
                
            pdf.ln(8)
            
        # 3. Dynamic Institutional Callout Footer Box
        current_y = pdf.get_y()
        pdf.set_fill_color(248, 250, 252)
        pdf.rect(10, current_y, 190, 16, 'F')
        pdf.set_fill_color(100, 116, 139)
        pdf.rect(10, current_y, 1.5, 16, 'F')
        
        pdf.set_x(15)
        pdf.set_font("Arial", "B", 8.5)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(0, 5, "Analytical Guardrail Protocol:", ln=True)
        pdf.set_x(15)
        pdf.set_font("Arial", "I", 8)
        pdf.set_text_color(71, 85, 105)
        pdf.cell(0, 4, "All baseline forecasting models incorporate a normalized statutory 25% corporate tax configuration layer.", ln=True)

        pdf.output(OUTPUT_REPORT_PATH)
        return f"SUCCESS: PDF statement compiled and written to target layout path: '{OUTPUT_REPORT_PATH}'."
    except Exception as e:
        return f"System generation failed during PDF printing processes: {str(e)}"

# Collection array utilized during graph node bindings
all_tools = [get_stock_analysis, generate_pdf_report]