# tools.py
import yfinance as yf
from fpdf import FPDF
from langchain_core.tools import tool
from config import OUTPUT_REPORT_PATH

@tool
def get_stock_analysis(ticker: str) -> dict:
    """
    Fetches real-time market data, valuation metrics (P/E and P/B ratios), 
    and general business summaries from Yahoo Finance for a specified company ticker.
    """
    try:
        # Standard cleaning of ticker strings to match yfinance expectations
        ticker_clean = ticker.strip().upper()
        stock = yf.Ticker(ticker_clean)
        info = stock.info
        
        # Safely parsing the dictionary to prevent KeyError failures
        return {
            "Ticker": ticker_clean,
            "Current Price": info.get("currentPrice"),
            "Market Cap": info.get("marketCap"),
            "P/E Ratio": info.get("trailingPE"),
            "P/B Ratio": info.get("priceToBook"),
            "Business Summary": info.get("longBusinessSummary", "")[:500] + "..."
        }
    except Exception as e:
        return {"error": f"Failed to retrieve data for ticker '{ticker}': {str(e)}"}

@tool
def generate_pdf_report(report_data: str) -> str:
    """
    Compiles complex analysis text generated by the LLM into a highly organized, 
    locally downloadable PDF statement.
    """
    try:
        # Initialize FPDF canvas canvas layout
        pdf = FPDF()
        pdf.add_page()
        
        # Setup clean header layouts
        pdf.set_font("Arial", "B", 16)
        pdf.cell(0, 12, "fin_intel | Automated Financial Analysis Report", ln=True, align="C")
        pdf.ln(8)
        
        # Format the core body content
        pdf.set_font("Arial", size=11)
        
        # Student Note: Clean up complex symbols from Gemini to prevent standard FPDF encoding errors
        clean_text = report_data.encode('latin-1', 'ignore').decode('latin-1')
        pdf.multi_cell(0, 8, clean_text)
        
        # Export text chunk down to localized workspace asset
        pdf.output(OUTPUT_REPORT_PATH)
        return f"SUCCESS: PDF statement compiled and written to target layout path: '{OUTPUT_REPORT_PATH}'."
    except Exception as e:
        return f"System generation failed during PDF printing processes: {str(e)}"

# Collection array utilized during graph node bindings
all_tools = [get_stock_analysis, generate_pdf_report]